name:  Combined Workflow lab_9/3
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      - name: Build
        run: dotnet build lab_9.csproj
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      - name: Run tests
        run: dotnet test lab_9.csproj --configuration ${{matrix.configuration }}
  analyze:
   needs: build
   runs-on: ubuntu-latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v4
   - name: Run code analysis
     run: dotnet restore lab_9/lab_9.csproj && dotnet tool install -g dotnet-format && dotnet format lab_9/lab_9.csproj

   

  
